### ISSUE TITLE
Tech Edit

### ISSUE THREAD

**Issue by atuttle** [atuttle/preso-closures#1]
@seancorfield @russplaysguitar 

If you guys could flip through the presentation and make sure everything I'm saying is technically correct, that would be most helpful.

I have checked and double checked all of the claims about the way ACF and Railo work, so there's no need to check that, but the closures-concept stuff is kind of amorphous and hard to prove. If you give it your stamp of approval, at least I'll know I'm pretty darn close. :)

**Comment by russplaysguitar** [comment]
The section "How can I use closures" implies that the use of the new set of FP functions have to do with closures, but actually they are just using functional expressions. See: http://www.bennadel.com/blog/2331-ColdFusion-10-Beta-Closures-And-Function-Expressions.htm

**Comment by russplaysguitar** [comment]
Also, this article covers some good myths about closures: http://javascriptweblog.wordpress.com/2010/10/25/understanding-javascript-closures/ 

One interesting myth was that they are only created by functions within functions, when actually any function technically creates a closure.

**Comment by seancorfield** [comment]
I gave Adam some feedback in IRC and agree with Russ that most of the preso is about callbacks and function expressions and really has nothing to do with closures. In addition, the explanation of closures and scope chains is really confusing.

The term "closure" was coined by Peter J. Landin - in 1964 - and really has nothing to do with Alonzo Church's Lambda Calculus (which was created in the 1930's). Nor are closures anything to do with CPS - which is a whole separate style of programming that does not need closures, just the ability to pass functions as arguments (i.e., callbacks). In addition, asynchronous programming has nothing to do with closures either - Node.js relies on callbacks, not closures.

**Comment by atuttle** [comment]
Thanks for the feedback, guys. I really appreciate you taking the time!

> @russplaysguitar: The section "How can I use closures" implies that the use of the new set of FP functions have to do with closures, but actually they are just using functional expressions.

I said as much on the slide at the bottom of that column. I simply labeled them that way because that's how they're presented in the docs, but I will explain that the way these are used is not (strictly) closures. You _could_ use closures with them, but none of them _require_ closures.

---

> @russplaysguitar: One interesting myth was that they are only created by functions within functions, when actually any function technically creates a closure.

I actually intended to cover this as well. I guess I forgot to put it in the speaker notes. I'll add that today.

---

> @seancorfield: most of the preso is about callbacks and function expressions and really has nothing to do with closures

I can see how it would come off that way from just the slides, but I really do intend to draw a distinction between them. The reason I spend time on function objects up front is that they're the foundational knowledge you have to understand before you can get closures.

Additionally, as of CF10, there are _no_ language features that _require_ closures; and I've been specifically told that I can not leak anything new about CF11.

As for the _"[most of the preso] really has nothing to do with closures"_ part, well, there's not much to explain? Access to free-variables when the closure is executed. I'm also covering where these free variables fall in the scope chain and how that affects references in various scenarios. Is there more to it than that? Maybe I'm missing something?

---

> @seancorfield:  the explanation of closures and scope chains is really confusing

I'll grant you that I may have botched some closure stuff up, but how is my explanation of scope chain confusing?

You make an unscoped variable reference. How do you find its value? Go down the list until you find a match. Can it get any simpler?

---

> @seancorfield: The term "closure" was coined by Peter J. Landin - in 1964 - and really has nothing to do with Alonzo Church's Lambda Calculus

Sorry about the mixup here. I had a lot of notes on the history and application of closures and trying to condense it down into slides was a lot harder than I anticipated. Guess I got some wires crossed somewhere.

---

> @seancorfield: Nor are closures anything to do with CPS

[Wikipedia](http://en.wikipedia.org/wiki/Closure_%28computer_science%29#Applications): (first sentence of this section)

> Closures are used to implement continuation-passing style, and in this manner, hide state. 

Do you disagree with wikipedia? If so, care to explain? My understanding is basically that you can use a closure as a callback in order to hide state (or in the case of javascript, even simply create private variables).

---

> @seancorfield: asynchronous programming has nothing to do with closures either

Yep. This is another distinction I intend to draw. Just have to build a foundation of function-object understanding before we can stand on it.

---

Perhaps I should throw in something toward the beginning that says something like: 

> The hardest part of learning closures is understanding function-objects (callbacks) and how they work. Once you get that straight, closures are a simple addition.

That would be an honest, authentic representation of my knowledge of the matter and would explain why the preso is laid out the way it is, so there are no surprises or disappointments.

**Comment by russplaysguitar** [comment]
> As for the "[most of the preso] really has nothing to do with closures" part, well, there's not much to explain? Access to free-variables when the closure is executed. I'm also covering where these free variables fall in the scope chain and how that affects references in various scenarios. Is there more to it than that? Maybe I'm missing something?

A review of [curry](https://github.com/markmandel/Sesame#_curryfunction-func-array-args--function) and/or [partial](http://underscorejs.org/#partial) (maybe [contrasting the two](https://en.wikipedia.org/wiki/Currying#Contrast_with_partial_function_application)?) could be a good way to show off how to use closures and have a deeper discussion on the subject, since those functions utilize closures internally to work. 

It would be nice to see an example or two in your preso where a closure is the best solution for the problem, especially if you compare that to a less -than-elegant solution without closures.

As far as the scope-chain stuff, I think it is pretty interesting, but you shouldn't let that dominate your preso (not sure how much time you were planning on spending on that). Maybe come up with 3-5 specific facts/features about closures that you want the audience to come away with?

**Comment by atuttle** [comment]
> A review of curry and/or partial (maybe contrasting the two?)

Excellent idea!

> It would be nice to see an example or two in your preso where a closure is the best solution for the problem, especially if you compare that to a less -than-elegant solution without closures.

I thought the same thing but I'm struggling to come up with any examples for CFML other than things like curry. I honestly can't remember ever thinking, "I wish we had closures in CFML." (Anonymous functions, yes, but not closures.)

I will add a wrap-up slide toward the end, too: Closures are just functions, all functions are closures, etc... Thanks for that suggestion.

**Comment by seancorfield** [comment]
Re: wikipedia - if you read the CPS stuff, there is no mention of closures because - like many higher-order function operations - CPS does not require closures. I actually do think it's misleading for the closure page on wikipedia to claim closure are used to implement CPS. FWIW, I did CPS work back in the early 80's in Pascal which absolutely did NOT have closures! :)

I think some reordering could reduce the confusion. Don't introduce the scope chain lookup until you've already shown a genuine closure with a "closed over" variable in it. Part of the confusion stems from your examples not being closures (throughout the preso, but specifically around the scope chain stuff).

I'd say introduce callbacks and establish those, with references to JS / Node.js / async. Show examples. Then show a genuine closure example, and THEN show the scope chain rules that determine how the "closed over" variable is handled (although frankly I find those closure-scopes to be the most confusing explanation I've ever seen of closures, based on how they are explained in OTHER languages!). Do the Adobe docs REALLY explain them in terms of those four or five scope chain injections?? It's a horrible explanation if that's the case.

**Comment by seancorfield** [comment]
Good examples of closures are functions that return functions (closures) where the returned function has "closed over" arguments passed to the original function:

Classic map / reduce / filter:

function add2(n) { return n + 2; }

a2 = a1.map( add2 );

function adder(i) { return function(n) { return n + i; }; }

a3 = a1.map( adder(2) );

function matches(s) { return function(ss) { return s == ss; }; }

a5 = a4.filter( matches("Sean") );

Hope that helps?

**Comment by atuttle** [comment]
> Do the Adobe docs REALLY explain them in terms of those four or five scope chain injections?? It's a horrible explanation if that's the case.

No, explaining closures in the context of scope chain was my idea. :(

Maybe I've overcomplicated the scope chain explanation, but I still feel it's (in some hopefully simple and understandable form) an important part of the discussion because it informs WHY variables are found where they are and how you have to name your variables when creating closures. (and now that I mention this, I should probably add that to the preso)

**Comment by atuttle** [comment]
> Classic map / reduce / filter:
> 
> function add2(n) { return n + 2; }
> 
> a2 = a1.map( add2 );
> 
> function adder(i) { return function(n) { return n + i; }; }
> 
> a3 = a1.map( adder(2) );
> 
> function matches(s) { return function(ss) { return s == ss; }; }
> 
> a5 = a4.filter( matches("Sean") );
> 
> Hope that helps?

It does help but the hard part is that CF doesn't support map yet. Is it introducing too much at once to use a library function that implements map?

**Comment by russplaysguitar** [comment]
Since map, reduce, and filter have their basis in lambda calculus, I don't think it is too much to discuss them at a conceptual level. You could also write examples in native JS if you don't want to introduce library-specific syntax.

**Comment by russplaysguitar** [comment]
This MDN page has some practical examples: [Closures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Closures?redirectlocale=en-US&redirectslug=JavaScript%2FGuide%2FClosures)

**Comment by seancorfield** [comment]
Feel free to borrow as much code as you want from here:

https://github.com/seancorfield/cfo2013/tree/master/polyglot

That's from my polyglot cf.O talk where I covered callbacks and closures and gave examples in JavaScript, Groovy and CFML.

Slides here http://corfield.org/articles/polyglot.pdf

**Comment by atuttle** [comment]
@seancorfield @russplaysguitar 

I just pushed a new branch: https://github.com/atuttle/preso-closures/tree/reorg

... in which I've incorporated much of your feedback, including the re-organization, Sean.

I still have more to do -- more examples of real closure usage in CFML, and I want to completely redo the closures in JS column, but I have to step away from the computer for a bit and figured it was best to push what I have so far.

Again, I really appreciate your comments. Thanks so much!

**Comment by seancorfield** [comment]
Cool. I will take a look once I'm back from vacation on Monday!

**Comment by seancorfield** [comment]
The reorg looks really good. The only slight inconsistency now is slide 4 says Closures are more than just functions, but slides 14/1 and 14/2 say Closures are just functions and All functions are closures... which is a bit confusing :)

**Comment by atuttle** [comment]
Awesome, thanks for taking the time to review!

**Comment by atuttle** [comment]
Alright gents. After making some final adjustments and clarifying the confusion Sean mentioned, I just merged the reorg branch into master (really like the new flow, thanks Sean!) and pushed. Save for the inevitable last minute tweaks inspired by other presentations, I think I'm done!

**Comment by seancorfield** [comment]
Looks great! I look forward to seeing this at cf.Objective() 2014 :)

**Comment by russplaysguitar** [comment]
Congrats! Hope to see a video of it online.

**Comment by seancorfield** [comment]
Seems like this could be closed now? 🙂
